# Copyright (C) 2025 Tudlang
# 
# This file is part of AralTools.
# 
# AralTools is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# AralTools is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with AralTools.  If not, see <http://www.gnu.org/licenses/>.

name: araltools
description: A suite of tools for students.
repository: https://github.com/tudlang/araltools
publish_to: "none"


version: "0.3.0+9"

environment:
  sdk: ^3.1.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  path: ^1.9.0
  timetable_view: ^0.3.0
  vector_math: ^2.1.4
  html: ^0.15.2
  http: ^1.3.0
  go_router: ^14.8.1
  multi_split_view: ^3.6.0
  #webview_universal: ^0.0.4
  desktop_webview_window: ^0.2.3
  #webview_win_floating: ^2.0.0 #THIS PLUGIN IS COMPATIBLE WITH 1st PARTY WEBVIEWS, BUT IS BLOCKED BY CLOUDFLARE
  #webview_flutter: ^4.2.0 
  string_unescape: ^2.0.0
  provider: ^6.1.2
  collection: ^1.19.1
  slang: ^4.5.0
  slang_flutter: ^4.5.0
  material_design_icons_flutter: ^7.0.7296
  async: ^2.13.0
  fluent_ui: ^4.11.2
  url_launcher: ^6.3.1
  path_provider: ^2.0.15
  package_info_plus: ^8.3.0
  simple_timetable: ^1.0.3
  screenshot: ^3.0.0
  file_picker: ^9.1.0
  archive: ^4.0.4
  xml: ^6.5.0
  flex_color_picker: ^3.7.0
  window_manager: ^0.4.3
  shared_preferences: ^2.5.2
  flutter_widget_from_html_core: ^0.16.0

dev_dependencies:
  build_runner: ^2.4.15
  build_web_compilers: ^4.1.2
  lints: ^5.1.1
  icons_launcher: ^3.0.1
  msix: ^3.16.8

flutter:
  uses-material-design: true
  
  fonts:
    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf

# Configuration for the msix package
msix_config:
  display_name: AralTools
  publisher_display_name: Tudlang
  identity_name: 57524Tudlang.36328D364A110
  logo_path: logo.png
  trim_logo: false
  languages: en, tl
  file_extension: .atsm
  store: true
  publisher: CN=B047DE3F-8CD3-4F98-BFCF-D353C8DE5B96